name: Update Events YAML

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (or Node.js if using JavaScript)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      # Step 4: Run the sync script
      - name: Run Facebook API sync script
        env:
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: |
          echo "hello"

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add events.yaml
          git commit -m "Daily update of events.yaml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
